LOAD DATA LOCAL INFILE "e:\\phpStudy\\WWW\\xubao\\data\\dq_cbinfo.txt"
INTO TABLE test.xubaomain CHARACTER SET GBK
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n';